version: '2.1'
services:
  app:
    image: satrapu/dotnet-core-with-docker-sh
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      DB_CONNECTION_STRING: "Host=db; Port=5432; Database=${db_name}; Username=${db_username}; Password=${db_password};"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:10.4-alpine
    healthcheck:
      test: >
        pg_isready \
          --dbname=${db_name} \
          --username=${db_username}
      interval: ${db_healthcheck_interval}
      timeout: ${db_healthcheck_timeout}
      retries: ${db_healthcheck_retries}
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - 5432
    volumes:
      - dotnet-core-with-docker-postgres-data:/var/lib/postgresql/data
volumes:
  dotnet-core-with-docker-postgres-data: