version: '3.6'
services:
  app:
    image: satrapu/dotnet-core-with-docker-console-runner
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      DB_CONNECTION_STRING: "Host=db; Port=5432; Database=${db_name}; Username=${db_username}; Password=${db_password};"
    depends_on:
      - db
  check_db_connectivity:
    image: satrapu/check-db-connectivity
    build:
      context: ./check-db-connectivity
    stdin_open: true
    tty: true
    environment:
      DB_HOST: db
      DB_NAME: ${db_name}
      DB_USERNAME: ${db_username}
      DB_PORT: 5432
      PORT_CHECKING_SLEEP: ${port_checking_sleep}
      PORT_CHECKING_ATTEMPTS: ${port_checking_attempts}
    depends_on:
      - db
  db:
    image: postgres:10.4-alpine
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - 5432
    volumes:
      - dotnet-core-with-docker-postgres-data:/var/lib/postgresql/data
volumes:
  dotnet-core-with-docker-postgres-data: