version: '3.6'
services:
  app:
    image: satrapu/dotnet-core-with-docker-console-runner
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      DB_CONNECTION_STRING: "Host=db; Port=5432; Database=${db_name}; Username=${db_username}; Password=${db_password};"
      DB_NAME: ${db_name}
      DB_SERVICE_NAME: db
      CHECK_DB_SLEEP: ${check_db_sleep}
      CHECK_DB_RETRIES: ${check_db_retries}
      DOCKER_API_VERSION: ${docker_api_version}
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock        
  db:
    image: postgres:10.4-alpine
    healthcheck:
      test: >
        pg_isready \
          --dbname=${db_name} \
          --username=${db_username}
      interval: ${db_healthcheck_interval}
      timeout: ${db_healthcheck_timeout}
      retries: ${db_healthcheck_retries}
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - 5432
    volumes:
      - dotnet-core-with-docker-postgres-data:/var/lib/postgresql/data
volumes:
  dotnet-core-with-docker-postgres-data: